// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krffvcdshgvuguzdpzbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyZmZ2Y2RzaGd2dWd1emRwemJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTQ1NjEsImV4cCI6MjA3MjczMDU2MX0.tO4NoEX2_-qLf_9C4HvHTdvx03KFmjp7Xq7NqAHvBiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});